---
- name: restart whoami
  ansible.builtin.debug:
    msg: "Whoami container would be restarted (skipped in check mode)"
  when: ansible_check_mode | default(false)

- name: restart whoami
  ansible.builtin.command:
    cmd: podman restart {{ whoami_container_name }}
  when: not (ansible_check_mode | default(false))