---
# Container configuration
traefik_version: "v3.5"
traefik_image: "docker.io/traefik:{{ traefik_version }}"
traefik_container_name: "traefik"
traefik_restart_policy: "unless-stopped"
traefik_network: "proxy"
traefik_log_max_size: "5m"

# Traefik configuration directory
traefik_config_dir: "/etc/traefik"

# https
traefik_https_port: 443

# http
traefik_http_port: 80
traefik_with_http_entrypoint: true
traefik_with_https_redirect: true

# Volume for SSL certificates
traefik_certs_volume: "ssl-certs"

# Dashboard configuration
traefik_with_dashboard: true
traefik_dashboard_insecure: false
traefik_dashboard_service_name: "traefik.{{ domain_name }}"
traefik_dashboard_route_enabled: false

# Logging
traefik_log_level: "DEBUG"

# Certificate resolvers
traefik_default_cert_resolver: "letsencrypt"
traefik_cert_resolvers:
  letsencrypt:
    ca_server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "tom-robin.raja@uk-koeln.de"
    tls_challenge: true
  letsencrypt-staging:
    ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: "tom-robin.raja@uk-koeln.de"
    tls_challenge: true
