---
- name: Deploy whoami container
  containers.podman.podman_container:
    name: "{{ whoami_container_name }}"
    image: "{{ whoami_image }}"
    state: started
    restart_policy: "{{ whoami_restart_policy }}"
    network: "{{ whoami_network }}"
    hostname: "{{ whoami_app_name }}.{{ app_internal_domain }}"
    log_opt:
      max_size: "{{ whoami_log_max_size }}"
  notify: restart whoami