---
- name: Ensure Traefik directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ traefik_config_dir }}"
    - "{{ traefik_config_dir }}/conf.d"

- name: Create Traefik configuration
  ansible.builtin.template:
    src: traefik.yaml.j2
    dest: "{{ traefik_config_dir }}/traefik.yaml"
    mode: '0644'
  notify: restart traefik

- name: Deploy Traefik dashboard route configuration
  ansible.builtin.template:
    src: traefik-dashboard.yaml.j2
    dest: "{{ traefik_config_dir }}/conf.d/traefik-dashboard.yaml"
    mode: '0644'
  notify: restart traefik
  when: traefik_dashboard_route_enabled | bool

- name: Create proxy network
  containers.podman.podman_network:
    name: "{{ traefik_network }}"
    state: present
  when: traefik_network != "host"

- name: Create SSL certificates volume
  containers.podman.podman_volume:
    name: "{{ traefik_certs_volume }}"
    state: present

- name: Deploy Traefik container
  containers.podman.podman_container:
    name: "{{ traefik_container_name }}"
    image: "{{ traefik_image }}"
    state: started
    restart_policy: "{{ traefik_restart_policy }}"
    network: "{{ traefik_network }}"
    ports: "{{ traefik_ports }}"
    volumes:
      - "{{ traefik_config_dir }}:/etc/traefik:ro"
      - "{{ traefik_certs_volume }}:/ssl-certs"
    log_opt:
      max_size: "{{ traefik_log_max_size }}"
  vars:
    traefik_ports: "{{ [traefik_http_port ~ ':' ~ traefik_http_port, traefik_https_port ~ ':' ~ traefik_https_port] if traefik_with_http_entrypoint else [traefik_https_port ~ ':' ~ traefik_https_port] }}"