---
- name: Deploy local app from Containerfile
  hosts: localhost
  connection: local
  vars:
    domain_name: "{{ ansible_fqdn }}"
    app_dir: "{{ lookup('env', 'PWD') }}"
  roles:
    - role: containerfile_app
      vars:
        containerfile_app_directory: "{{ app_dir }}"